branch-defaults:
  development:
    environment: null
global:
  application_name: clerkr
  default_ec2_keyname: null
  default_platform: Ruby 2.1 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
